package proyectotercerparcial;

import java.awt.Desktop;
import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YAEL
 */
public class FrmAlbumUsuario extends javax.swing.JFrame {

    int noClave = -1;
    double saldoTotal;
    double gasto;
    double cont = 0;
    Archivo archivo = new Archivo("Canciones.txt");
    Archivo archivoCompras = new Archivo("CancionesCompradas.txt");
    ArchivoPerfilUsuario archivoPerfilUsuario = new ArchivoPerfilUsuario("Clientes.txt");
    ArchivoSaldo archivoSaldo = new ArchivoSaldo("Saldo.txt");

    ArrayList<Cancion> listaCanciones = new ArrayList<>();
    ArrayList<Cancion> listaCancionesCompradas = new ArrayList<>();
    ArrayList<RegistroPerfilUsuario> listaUsuario = new ArrayList<>();
    ArrayList<Saldo> listaSaldo = new ArrayList<>();

    /**
     * Creates new form FrmAlbum1
     */
    public FrmAlbumUsuario() {
        initComponents();
        setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Iconos/101-headset.png")).getImage());

        listaCanciones = archivo.leerArchivo();
        llenarTablaCanciones();

        listaCancionesCompradas = archivoCompras.leerArchivo();
        llenarCancionesCompradas();
        //System.out.println("" + saldoTotal);

        listaSaldo = archivoSaldo.leerArchivo();
        for (Saldo aux : listaSaldo) {
            saldoTotal = aux.obtenerSaldo();
            //System.out.println("" + saldoTotal);
            txtSaldoTotal.setText("" + saldoTotal);
        }

    }

    private void llenarTablaCanciones() {
        DefaultTableModel llenar
                = (DefaultTableModel) tablaCancionesDisponibles
                        .getModel();
        Object[] fila = new Object[8];
        for (int i = 0; i < tablaCancionesDisponibles.getRowCount(); i++) {
            llenar.removeRow(i);
            i = i - 1;
        }
        //llenar tabla
        for (Cancion aux : listaCanciones) {
            fila[0] = aux.getClave();
            fila[1] = aux.getNombreCancion();
            fila[2] = aux.getNombreCantante();
            fila[3] = aux.getGenero();
            fila[4] = aux.getPortada();
            fila[5] = aux.getAlbum();
            fila[6] = aux.getArchivo();
            fila[7] = aux.getPrecio();
            llenar.addRow(fila);
        }

    }

    public void LimpiarCajas() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtSaldo.setText("");
    }

    private void llenarCancionesCompradas() {
        DefaultTableModel llenar
                = (DefaultTableModel) tablaCancionesCompradas
                        .getModel();
        Object[] fila = new Object[8];
        for (int i = 0; i < tablaCancionesCompradas.getRowCount(); i++) {
            llenar.removeRow(i);
            i = i - 1;
        }
        //llenar tabla
        for (Cancion aux : listaCancionesCompradas) {
            fila[0] = aux.getClave();
            fila[1] = aux.getNombreCancion();
            fila[2] = aux.getNombreCantante();
            fila[3] = aux.getGenero();
            fila[4] = aux.getPortada();
            fila[5] = aux.getAlbum();
            fila[6] = aux.getArchivo();
            fila[7] = aux.getPrecio();
            llenar.addRow(fila);
        }

    }

    private boolean buscar() {
        for (Cancion aux : listaCancionesCompradas) {
            if (noClave == aux.getClave()) {
                return true;
            }
        }
        return false;
    }

    public boolean verificarCajas() {

        try {
            if (txtNombre.getText().compareTo("") == 0) {
                throw new Exception(
                        "Debe poner la clave");
            }
            if (txtApellido.getText().compareTo("") == 0) {
                throw new Exception(
                        "Debe poner el nombre de la cancion");
            }
            if (txtSaldo.getText().compareTo("") == 0) {
                throw new Exception(
                        "Debe poner el precio");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage());
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        btnAgregarPerfil = new javax.swing.JButton();
        txtApellido = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtCuenta = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaCancionesCompradas = new javax.swing.JTable();
        btnVerPagina = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtClaveBuscar = new javax.swing.JTextField();
        btnBuscarClave = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaCancionesDisponibles = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtSaldoTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtModificarSaldo = new javax.swing.JTextField();
        btnAgregarSaldo = new javax.swing.JButton();
        btnVerPagina1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        image = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDatos = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu del usuario");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 150, -1));

        btnAgregarPerfil.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgregarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/101-pay-point_15x15.png"))); // NOI18N
        btnAgregarPerfil.setText("Agregar");
        btnAgregarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPerfilActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 150, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nombre:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Saldo a Agregar:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Apellidos:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        txtSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoActionPerformed(evt);
            }
        });
        jPanel1.add(txtSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 130, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/x-button_15x15.png"))); // NOI18N
        jButton1.setText("Cerrar Sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, -1, -1));
        jPanel1.add(txtCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 150, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Cuenta:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel15.setText("jLabel15");
        jLabel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 340, 330));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/12. Lil Pump - Whippin' (ft. Famous Dex)-01.jpeg"))); // NOI18N
        jLabel17.setText("jLabel17");
        jLabel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 330, 290));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Registro de usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jLabel16.setText("jLabel16");
        jLabel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 360, 330));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2ff1cbf1a702f5105a70175ffa10f3dc.jpg"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 520));

        jTabbedPane1.addTab("Registro de usuario", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaCancionesCompradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Clave", "Cancion", "Cantante", "Genero", "Portada", "Album", "Archivo", "Precio"
            }
        ));
        tablaCancionesCompradas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCancionesCompradasMouseClicked(evt);
            }
        });
        tablaCancionesCompradas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaCancionesCompradasKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tablaCancionesCompradas);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 800, 126));

        btnVerPagina.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVerPagina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/101-investment-3_15x15.png"))); // NOI18N
        btnVerPagina.setText("Ver canciones compradas");
        btnVerPagina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPaginaActionPerformed(evt);
            }
        });
        jPanel2.add(btnVerPagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, -1, -1));

        btnBorrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/x-button_15x15.png"))); // NOI18N
        btnBorrar.setText("Borrar compra");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, -1));

        btnComprar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnComprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/101-taxes_15x15.png"))); // NOI18N
        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        jPanel2.add(btnComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Dame clave a buscar:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, -1, -1));
        jPanel2.add(txtClaveBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 100, -1));

        btnBuscarClave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBuscarClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/101-stats-6_15x15.png"))); // NOI18N
        btnBuscarClave.setText("Buscar clave");
        btnBuscarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, -1, -1));

        tablaCancionesDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Clave", "Cancion", "Cantante", "Genero", "Portada", "Album", "Archivo", "Precio"
            }
        ));
        tablaCancionesDisponibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCancionesDisponiblesMouseClicked(evt);
            }
        });
        tablaCancionesDisponibles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaCancionesDisponiblesKeyReleased(evt);
            }
        });
        jScrollPane6.setViewportView(tablaCancionesDisponibles);

        jPanel2.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 800, 123));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Saldo total:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        txtSaldoTotal.setEditable(false);
        txtSaldoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoTotalActionPerformed(evt);
            }
        });
        jPanel2.add(txtSaldoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 100, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Canciones compradas");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Modificar Saldo:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        txtModificarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModificarSaldoActionPerformed(evt);
            }
        });
        jPanel2.add(txtModificarSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 80, -1));

        btnAgregarSaldo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgregarSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/101-pay-point_15x15.png"))); // NOI18N
        btnAgregarSaldo.setText("Agregar Saldo");
        btnAgregarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSaldoActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregarSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        btnVerPagina1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVerPagina1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/101-investment-3_15x15.png"))); // NOI18N
        btnVerPagina1.setText("Ver catalogo de canciones");
        btnVerPagina1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPagina1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnVerPagina1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Canciones disponibles para comprar");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 820, 230));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/101-safe-box_15x15.png"))); // NOI18N
        jButton2.setText("Editar genero");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, -1, -1));

        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 820, 230));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Artist--1448957995-tumblr_mqqns962mj1re5stco1_r2_1280.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 520));

        jTabbedPane1.addTab("Comprar canciones", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 130, -1));

        image.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 255)));
        jPanel3.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 310, 220));

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/101-stats-6_15x15.png"))); // NOI18N
        btnBuscar.setText("Buscar clave");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        txtDatos.setBackground(new java.awt.Color(102, 102, 102));
        txtDatos.setColumns(20);
        txtDatos.setForeground(new java.awt.Color(255, 255, 255));
        txtDatos.setRows(5);
        txtDatos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(txtDatos);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 370, 200));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Buscar los datos de las canciones comprada");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/PatternCalaveras72.jpg"))); // NOI18N
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 290, 130));

        jLabel20.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(255, 255, 255)));
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 310, 150));

        jLabel29.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 420, 370));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5442.jpg"))); // NOI18N
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 520));

        jTabbedPane1.addTab("Busqueda datos de la cancion comprada", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPerfilActionPerformed
        int Cuenta = Integer.parseInt(txtCuenta.getText());
        String Nombre = txtNombre.getText();
        String Apellido = txtApellido.getText();
        double dinero = Double.parseDouble(txtSaldo.getText());
        RegistroPerfilUsuario registro = new RegistroPerfilUsuario(Cuenta, Nombre, Apellido,
                dinero);
        listaUsuario.add(registro);
        archivoPerfilUsuario.EscribirArchivo(listaUsuario);
        JOptionPane.showMessageDialog(this, "Registro dado de alta");
        txtSaldoTotal.setText(txtSaldo.getText());
        archivoSaldo.EscribirArchivo(listaSaldo);
        // BORRA LA CAJA
        txtCuenta.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtSaldo.setText("");

        //archivoPerfilUsuario.EscribirArchivo(listaUsuario);
        // textArea.setText(txtNombre.getText());
        // textArea.setText(txtApellido.getText());
        //textArea.setText(txtSaldo.getText());
        //JOptionPane.showMessageDialog(this, "Registro dado de alta");

    }//GEN-LAST:event_btnAgregarPerfilActionPerformed

    private void btnBuscarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClaveActionPerformed
        if (txtClaveBuscar.getText().compareTo("") == 0) {
            llenarTablaCanciones();
            return;
        }
        int claveB;
        try {
            claveB = Integer.parseInt(txtClaveBuscar.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe escibir numero");
            return;
        }
        DefaultTableModel llenar = (DefaultTableModel) tablaCancionesCompradas.getModel();
        Object[] fila = new Object[8];
        //limpiar tabla
        for (int i = 0; i < tablaCancionesCompradas.getRowCount(); i++) {
            llenar.removeRow(i);
            i = i - 1;
        }
        //PONER EL ELEMENTO EN LA TABLA, SI LO ENCUENTRA
        for (Cancion aux : listaCanciones) {
            if (aux.getClave() == claveB) {
                fila[0] = aux.getClave();
                fila[1] = aux.getNombreCancion();
                fila[2] = aux.getNombreCantante();
                fila[3] = aux.getGenero();
                fila[4] = aux.getPortada();
                fila[5] = aux.getAlbum();
                fila[6] = aux.getArchivo();
                fila[7] = aux.getPrecio();
                llenar.addRow(fila);

            }

        }
    }//GEN-LAST:event_btnBuscarClaveActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        if (noClave == -1) {
            JOptionPane.showMessageDialog(this, "Debe tener un registro activo");
            return;
        }
        if (buscar()) {
            JOptionPane.showMessageDialog(this, "Ya comprado");
            return;
        }
        for (Cancion aux : listaCanciones) {
            if (noClave == aux.getClave()) {
                listaCancionesCompradas.add(aux);
                llenarCancionesCompradas();
                listaCanciones.add(aux);
                archivoCompras.EscribirArchivo(listaCancionesCompradas);
                JOptionPane.showMessageDialog(this, "Comprada");
                return;

            }

        }
        double gasto = Double.parseDouble(txtSaldoTotal.getText());
        for (Saldo aux : listaSaldo) {
            aux.restarSaldo(gasto);
            txtSaldoTotal.setText("" + aux.obtenerSaldo());
            archivoSaldo.EscribirArchivo(listaSaldo);
        }

        //JOptionPane.showMessageDialog(this, "Comprado");
        /*int filaseleccionada = tablaCancionesDisponibles.getSelectedRow();
        try {
            String Precio;

            if (filaseleccionada == -1) {
                JOptionPane.showMessageDialog(null, "Debes seleccionar una canción", "Advertencia", 1);
            } else {
                m = (DefaultTableModel) tablaCancionesDisponibles.getModel();
                //Clave = tablaCancionesDisponibles.getValueAt(filaseleccionada, 0).toString();
                //Cancion = tablaCancionesDisponibles.getValueAt(filaseleccionada, 1).toString();
                //Cantante = tablaCancionesDisponibles.getValueAt(filaseleccionada, 2).toString();
                //Genero = tablaCancionesDisponibles.getValueAt(filaseleccionada, 3).toString();
                //Portada = tablaCancionesDisponibles.getValueAt(filaseleccionada, 4).toString();
                //Album = tablaCancionesDisponibles.getValueAt(filaseleccionada, 5).toString();
                //Archivo = tablaCancionesDisponibles.getValueAt(filaseleccionada, 6).toString();
                Precio = tablaCancionesDisponibles.getValueAt(filaseleccionada, 7).toString();

                m = (DefaultTableModel) tablaCancionesCompradas.getModel();
                String filaelemento[] = {Precio};
                m.addRow(filaelemento);

            }

        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Verificar seleccion de canción", "Error", 1);
            /*if (tablaCanciones.getSelectedRow() == filaseleccionada) {
                JOptionPane.showMessageDialog(this, "Ya esta en tu lista de compras");

            }*/
 /*double sumatoriaCargo = 0.0;
        int totalRowc = tablaCancionesCompradas.getRowCount();
        totalRowc -= 1;
        for (int i = 0; i <= (totalRowc); i++) {
            double suma = Double.parseDouble(String.valueOf(tablaCancionesCompradas.getValueAt(i, 7)));
            sumatoriaCargo += suma;
            txtDinero.setText("" + sumatoriaCargo);
        }*/

    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        if (noClave == -1) {
            JOptionPane.showMessageDialog(this, "Debe tener un registro activo");
            return;
        }
        int boton = JOptionPane.showConfirmDialog(this, "Desea borrar este elemento?",
                "Advertencia", JOptionPane.YES_NO_OPTION);
        if (boton == JOptionPane.YES_OPTION) {
            Iterator<Cancion> iteratorX = listaCancionesCompradas.iterator();
            while (iteratorX.hasNext()) {
                if (iteratorX.next().getClave() == noClave) {
                    iteratorX.remove();
                    JOptionPane.showMessageDialog(this, "Eliminado");
                    archivoCompras.EscribirArchivo(listaCancionesCompradas);
                    noClave = -1;
                    llenarCancionesCompradas();
                }
            }
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnVerPaginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPaginaActionPerformed
        PaginaWebCompras pagweb = new PaginaWebCompras("CancionesCompradas.html");
        pagweb.EscribirArchivo(listaCancionesCompradas);
        //abrir el archivo en el programador
        try {
            File pagina = new File("CancionesCompradas.html");
            Desktop.getDesktop().open(pagina);
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnVerPaginaActionPerformed

    private void tablaCancionesCompradasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaCancionesCompradasKeyReleased
        if (tablaCancionesCompradas.getSelectedRows().length > 0) {
            int fila = tablaCancionesCompradas.getSelectedRow();
            noClave = Integer.parseInt(String.valueOf(
                    tablaCancionesCompradas.getValueAt(fila, 0)));

        }
    }//GEN-LAST:event_tablaCancionesCompradasKeyReleased

    private void tablaCancionesCompradasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCancionesCompradasMouseClicked
        int fila = tablaCancionesCompradas.getSelectedRow();
        noClave = Integer.parseInt(String.valueOf(
                tablaCancionesCompradas.getValueAt(fila, 0)));
    }//GEN-LAST:event_tablaCancionesCompradasMouseClicked

    private void tablaCancionesDisponiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCancionesDisponiblesMouseClicked
        int fila = tablaCancionesDisponibles.getSelectedRow();
        noClave = Integer.parseInt(String.valueOf(
                tablaCancionesDisponibles.getValueAt(fila, 0)));
    }//GEN-LAST:event_tablaCancionesDisponiblesMouseClicked

    private void tablaCancionesDisponiblesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaCancionesDisponiblesKeyReleased

    }//GEN-LAST:event_tablaCancionesDisponiblesKeyReleased

    private void txtModificarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModificarSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModificarSaldoActionPerformed

    private void btnAgregarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSaldoActionPerformed
        double Agregar = Double.parseDouble(txtModificarSaldo.getText());
        for (Saldo aux : listaSaldo) {
            aux.agregarSaldo(Agregar);
            txtSaldoTotal.setText("" + aux.obtenerSaldo());
        }
        archivoSaldo.EscribirArchivo(listaSaldo);
        txtModificarSaldo.setText("");
        JOptionPane.showMessageDialog(this, "Agregado correctamente");
    }//GEN-LAST:event_btnAgregarSaldoActionPerformed

    private void btnVerPagina1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPagina1ActionPerformed
        PaginaWeb pagwec = new PaginaWeb("CancionesPrueba.html");
        pagwec.EscribirArchivo(listaCanciones);
        //abrir el archivo en el programador
        try {
            File pagina = new File("CancionesPrueba.html");
            Desktop.getDesktop().open(pagina);
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnVerPagina1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrmLoginUsuario P1 = new FrmLoginUsuario();
        P1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoActionPerformed

    private void txtSaldoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoTotalActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            int busca = Integer.parseInt(txtBuscar.getText());
            for (Cancion aux : listaCancionesCompradas) {
                if (aux.getClave() == busca) {
                    txtDatos.setText(aux.toString());
                    String path = "img/" + aux.getPortada() + ".jpg";
                    ImageIcon fot = new ImageIcon(path);
                    Icon icono2 = new ImageIcon(fot.getImage().getScaledInstance(
                            image.getWidth(), image.getHeight(),
                            Image.SCALE_DEFAULT));
                    image.setIcon(icono2);
                    this.repaint();
                    return;
                }
            }
            String path = "img/no.jpg";
            ImageIcon fot = new ImageIcon(path);
            Icon icono2 = new ImageIcon(fot.getImage().getScaledInstance(
                    image.getWidth(), image.getHeight(),
                    Image.SCALE_DEFAULT));
            image.setIcon(icono2);
            this.repaint();
            txtDatos.setText("No se encontro");
        } catch (NumberFormatException ex) {
            System.out.println("Error:" + ex);
            JOptionPane.showMessageDialog(this, "Debe ingresar valores enteros",
                    "Error", 0);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (noClave == -1) {
            JOptionPane.showMessageDialog(this, "Debe tener un registro activo");
            return;
        }
        for (Cancion aux : listaCancionesCompradas) {
            if (noClave == aux.getClave()) {
                FrmEditarUsuario frm = new FrmEditarUsuario(aux);
                frm.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAlbumUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAlbumUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAlbumUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAlbumUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAlbumUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPerfil;
    private javax.swing.JButton btnAgregarSaldo;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarClave;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnVerPagina;
    private javax.swing.JButton btnVerPagina1;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaCancionesCompradas;
    private javax.swing.JTable tablaCancionesDisponibles;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtClaveBuscar;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JTextArea txtDatos;
    private javax.swing.JTextField txtModificarSaldo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtSaldoTotal;
    // End of variables declaration//GEN-END:variables
}
